#lang racket
(define (gleich? liste)
  (define (gleich?-iter liste pos neg)
    (if (empty? liste)
      (= pos neg)
      (if (positive? (car liste))
        (gleich?-iter (cdr liste) (+ pos 1) neg)
        (if (negative? (car liste))
            (gleich?-iter (cdr liste) pos (+ neg 1))
            (gleich?-iter (cdr liste) pos neg)
            )
        )
      )
    )
  (gleich?-iter liste 0 0)
  )
