#lang racket
(define (osterformel j)
  (let ((a (remainder j 19)))
    (let ((b (remainder j 4)))
      (let ((c (remainder j 7)))
        (let ((k (floor (/ j 100))))
          (let ((p (floor (/ (+ (* 8 k) 13) 25))))
            (let ((q (floor (/ k 4))))
              (let ((M (remainder (- (+ 15 k) p q) 30)))
                (let ((N (remainder (- (+ 4 k) q) 7)))
                  (let ((d (remainder (+ (* 19 a) M) 30)))
                    (let ((e (remainder (+ (* 2 b) (* 4 c) (* 6 d) N) 7)))
                      (let ((o (+ 22 d e))) o)))))))))))
  )